(menu-bar-mode -1) 
(toggle-scroll-bar -1) 
(tool-bar-mode -1) 
(setq inhibit-startup-message t)
(global-display-line-numbers-mode t)
(setq display-line-numbers-type 'relative)
(show-paren-mode 1)
(set-default 'truncate-lines t)
(eldoc-mode 1)
(fset 'yes-or-no-p 'y-or-n-p)
(add-to-list 'default-frame-alist '(font . "JetBrains Mono 12"))
(indent-tabs-mode nil)
(global-subword-mode 1)
(setq indent-tabs-mode nil)
(setq scroll-margin 1)
(add-to-list 'default-frame-alist
             '(vertical-scroll-bars . nil))
